name: "gbraad's Dotfiles `machine` Action"
description: 'Wrapper for machine command execution on GitHub runners'
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  prefix:
    description: 'The virtual machine image to use'
    required: true
    default: ''
  command:
    description: 'Command to execute (download, start, console, etc.)'
    required: true
    default: 'start'
  as_user:
    description: 'User to run the commands as (optional)'
    required: false
    default: ""
outputs:
  prefix:
    description: 'The prefix (virtual machine image) that was used'
    value: ${{ inputs.prefix }}
runs:
  using: 'composite'
  steps:
    - name: Execute machine command
      uses: gbraad-actions/zsh-action@main
      with:
        as_user: ${{ inputs.as_user }}
        run: |
          # Check if machine function exists
          if ! type machine >/dev/null 2>&1; then
            echo "Error: machine function is not defined. Please make sure to run install first"
            exit 1
          fi
          
          # Execute machine command
          machine ${{ inputs.prefix }} ${{ inputs.command }} ${{ inputs.args }}
